// <auto-generated />
using BulkCopy.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BulkCopy.Infrastructure.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BulkCopy.Domain.Models.Transfer", b =>
                {
                    b.Property<int>("FromAccount")
                        .HasColumnType("integer");

                    b.Property<int>("ToAccount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TransferAmount")
                        .HasColumnType("numeric");

                    b.ToTable("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
